version: '3.6'

services:
  api:
    build: .
    depends_on:
      - db
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://postgres:admin@db:5432/postgres
    ports:
      - 5000:5000
    restart: always
  db:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    restart: always
